spring:
  jpa:
#    hibernate:
#      ddl-auto: create
    show-sql: true
    open-in-view: false
  data:
    web:
      pageable:
        page-parameter: page
        size-parameter: per_page
        max-page-size: 100
        default-page-size: 30
        one-indexed-parameters: true
  messages:
    basename: messages, cart_messages
  web:
    locale: en_US

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: shutdown

server:
  error:
    whitelabel:
      enabled: false
    include-exception: false
    include-stacktrace: never
    include-binding-errors: never

